POST http://localhost:4000/userRoute/create-user
Content-Type: application/json

{
    "userName": "Adarsh",
    "userEmail": "e@me.com",
    "userPasswd": "secret@123",
    "userRole": "User"
}

### user sign in endpoint
POST http://localhost:4000/userRoute/login
Content-Type: application/json

{
    "userEmail": "e@me.com",
    "userPasswd": "secret@123"
}
